#!/usr/bin/env bash                                                             
# This script that accepts one argument - whoami                                       
# It runs the 'whoami' command
sudo -u "$1" whoami
